### ISSUE TITLE
Exception importing component in Home Assistant 2023.6

### ISSUE THREAD

**Issue by gerliczky** [Emilv2/huawei_solar#104]
I got the following exception, when I try to use the component

```
2023-06-09 05:18:38.640 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.huawei_solar.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 1206, in _gcd_import
  File "", line 1178, in _find_and_load
  File "", line 1149, in _find_and_load_unlocked
  File "", line 690, in _load_unlocked
  File "", line 940, in exec_module
  File "", line 241, in _call_with_frames_removed
  File "/config/custom_components/huawei_solar/sensor.py", line 26, in 
    from huawei_solar import AsyncHuaweiSolar, ConnectionException, ReadException
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/__init__.py", line 6, in 
    from .huawei_solar import *  # noqa: F401 F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 15, in 
    from pymodbus.client.asynchronous.async_io import init_tcp_client
  File "/usr/local/lib/python3.11/site-packages/pymodbus/client/asynchronous/async_io/__init__.py", line 228, in 
    class ReconnectingAsyncioModbusTcpClient(object):
  File "/usr/local/lib/python3.11/site-packages/pymodbus/client/asynchronous/async_io/__init__.py", line 262, in ReconnectingAsyncioModbusTcpClient
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
```

Home Assistant 2023.6.1
Supervisor 2023.06.1
Frontend 20230607.0 - latest

**Comment by butsjoh** [comment]
I also had issue try to upgrade to 2023.6.0 yesterday. Something related to wrong yaml configuration or something. Not sure what i need todo to fix.

**Comment by gm27271** [comment]
I have same error After upgrade to
Home Assistant 2023.6.1
Supervisor 2023.06.1
Operating System 10.2
Interfejs użytkownika: 20230608.0 - latest

**Comment by 111lisu** [comment]
I have same error After upgrade to 
Home Assistant 2023.6.1
Supervisor 2023.06.1
Operating System 10.2
Interfejs użytkownika: 20230608.0 - latest

Platform error sensor.huawei_solar - Exception importing custom_components.huawei_solar.sensor

**Comment by gm27271** [comment]
If no feedback, then I Will consier going back to prvevious HA core version.

**Comment by butsjoh** [comment]
I had to revert back to get it working again. I have no clue what is going on. Probably the python bump to 3.11 is what is causing the issue but i am not an expert at this. It would a least be great if somebody can confirm that that would be the issue.

**Comment by butsjoh** [comment]
So i can confirm it is related to the python bump: https://stackoverflow.com/questions/74345065/attributeerror-module-asyncio-has-no-attribute-coroutine-in-python-3-11

**Comment by butsjoh** [comment]
@Emilv2 any fix that can be applied for this?

**Comment by titidnh** [comment]
You can upgrade the py package to a more recent version (manifest update)

{
  "domain": "huawei_solar",
  "name": "huawei_solar",
  "documentation": "https://github.com/Emilv2/huawei_solar",
  "dependencies": [],
  "codeowners": ["Emilv2"],
  "requirements": ["huawei-solar>=2.0.0,<=2.2.6"],
  "version": "1.2.4"
}

+ change the sensor.py file to use the new way to instantiate the class

        inverter = await AsyncHuaweiSolar.create(
            host=config[CONF_HOST], port=config[CONF_PORT], slave=config[CONF_SLAVE]
        )

It works back on my HA after those changes

**Comment by Emilv2** [comment]
@titidnh Thanks! I currently can't test it, if someone else confirms it works I will push it as a fix.

**Comment by butsjoh** [comment]
I can confirm it works as well ! thnx

**Comment by agmuz** [comment]
@titidnh  hi i change in sensor.py line 169 and 170 , dont work
    try:
        inverter = await AsyncHuaweiSolar.create(
            host=config[CONF_HOST], port=config[CONF_PORT], slave=config[CONF_SLAVE]
        )

could you paste the whole sensor.py file

**Comment by nalbor** [comment]
I've made those changes in manifest and sensor.py (line 169-170) and it didn't start working.

**Comment by titidnh** [comment]
import asyncio
import logging
from datetime import timedelta

import homeassistant.helpers.config_validation as cv
import voluptuous as vol
from homeassistant.components.sensor import (
    ATTR_LAST_RESET,
    ATTR_STATE_CLASS,
    PLATFORM_SCHEMA,
    STATE_CLASS_MEASUREMENT,
    STATE_CLASS_TOTAL_INCREASING,
)
from homeassistant.const import (
    CONF_HOST,
    DEVICE_CLASS_CURRENT,
    DEVICE_CLASS_ENERGY,
    DEVICE_CLASS_POWER,
    DEVICE_CLASS_VOLTAGE,
    ENERGY_KILO_WATT_HOUR,
    POWER_WATT,
)
from homeassistant.helpers.entity import Entity
from homeassistant.util.dt import utc_from_timestamp

from huawei_solar import AsyncHuaweiSolar, ConnectionException, ReadException

_LOGGER = logging.getLogger(__name__)


SCAN_INTERVAL = timedelta(seconds=60)

# don't overload the poor thing
DEFAULT_COOLDOWN_INTERVAL = 0.1
# throttle reconnect attempts
DEFAULT_RECONNECT_INTERVAL = 30

CONF_OPTIMIZERS = "optimizers"
CONF_BATTERY = "battery"
CONF_SLAVE = "slave"
CONF_PORT = "port"

STATE_REGISTER = "active_power"

ATTR_GRID_CODE = "grid_code"
ATTR_SERIAL_NUMBER = "serial_number"
ATTR_NB_PV_STRINGS = "nb_pv_strings"


STATIC_ATTR_LIST = [
    "model_id",
    "model_name",
    ATTR_SERIAL_NUMBER,
    "rated_power",
    ATTR_NB_PV_STRINGS,
]

STATIC_ATTR_GRID_LIST = [
    "grid_standard",
    "grid_country",
]

DYNAMIC_ATTR_LIST = [
    "day_active_power_peak",
    "reactive_power",
    "power_factor",
    "efficiency",
    "grid_frequency",
    "grid_voltage",
    "grid_current",
    "line_voltage_A_B",
    "line_voltage_B_C",
    "line_voltage_C_A",
    "phase_A_voltage",
    "phase_B_voltage",
    "phase_C_voltage",
    "phase_A_current",
    "phase_B_current",
    "phase_C_current",
    "power_meter_active_power",
    "input_power",
    "grid_A_voltage",
    "grid_B_voltage",
    "grid_C_voltage",
    "active_grid_A_current",
    "active_grid_B_current",
    "active_grid_C_current",
    "active_grid_power_factor",
    "active_grid_frequency",
    "daily_yield_energy",
    "accumulated_yield_energy",
    "grid_exported_energy",
    "grid_accumulated_energy",
    "active_grid_A_B_voltage",
    "active_grid_B_C_voltage",
    "active_grid_C_A_voltage",
    "active_grid_A_power",
    "active_grid_B_power",
    "active_grid_C_power",
    "startup_time",
    "shutdown_time",
    "internal_temperature",
    "device_status",
    "system_time",
]

ATTR_DAILY_YIELD = "daily_yield_energy"
ATTR_ACCUMULATED_YIELD = "accumulated_yield_energy"
ATTR_GRID_EXPORTED = "grid_exported_energy"
ATTR_GRID_ACCUMULATED = "grid_accumulated_energy"

ENTITY_SENSOR_LIST = [
    ATTR_DAILY_YIELD,
    ATTR_ACCUMULATED_YIELD,
    ATTR_GRID_EXPORTED,
    ATTR_GRID_ACCUMULATED,
]


ATTR_NB_OPTIMIZERS = "nb_optimizers"
ATTR_NB_ONLINE_OPTIMIZERS = "nb_online_optimizers"


ATTR_STORAGE_CHARGE_DISCHARGE_POWER = "storage_charge_discharge_power"
ATTR_STORAGE_TOTAL_CHARGE = "storage_total_charge"
ATTR_STORAGE_TOTAL_DISCHARGE = "storage_total_discharge"

BATTERY_ENTITY_SENSOR_LIST = [
    ATTR_STORAGE_CHARGE_DISCHARGE_POWER,
    ATTR_STORAGE_TOTAL_CHARGE,
    ATTR_STORAGE_TOTAL_DISCHARGE,
]


BATTERY_ATTR_LIST = [
    "storage_running_status",
    "storage_current_day_charge_capacity",
    "storage_current_day_discharge_capacity",
    "storage_working_mode_a",
    "storage_unit_1_working_mode_b",
    "storage_time_of_use_price",
    "storage_lcoe",
    "storage_maximum_charging_power",
    "storage_maximum_discharging_power",
    "storage_power_limit_grid_tied_point",
    "storage_charging_cutoff_capacity",
    "storage_discharging_cutoff_capacity",
    "storage_forced_charging_and_discharging_period",
    "storage_forced_charging_and_discharging_power",
    "storage_state_of_capacity",
]

PLATFORM_SCHEMA = PLATFORM_SCHEMA.extend(
    {
        vol.Required(CONF_HOST): cv.string,
        vol.Optional(CONF_OPTIMIZERS, default=False): cv.boolean,
        vol.Optional(CONF_BATTERY, default=False): cv.boolean,
        vol.Optional(CONF_SLAVE, default=0): int,
        vol.Optional(CONF_PORT, default=502): int,
    }
)


async def async_setup_platform(hass, config, async_add_entities, discovery_info=None):
    """Create the sensor."""
    _LOGGER.debug("Setup Huawei Inverter")

    static_attributes = {}

    try:
        inverter = await AsyncHuaweiSolar.create(
            host=config[CONF_HOST], port=config[CONF_PORT], slave=config[CONF_SLAVE]
        )

        for register in STATIC_ATTR_LIST:
            static_attributes[register] = (await inverter.get(register)).value
            _LOGGER.debug("get sensor static attribute: %s", register)
            await asyncio.sleep(DEFAULT_COOLDOWN_INTERVAL)

        register = ATTR_GRID_CODE
        tmp = (await inverter.get(register)).value
        _LOGGER.debug("get sensor static attribute: %s", register)
        static_attributes[STATIC_ATTR_GRID_LIST[0]] = tmp.standard
        static_attributes[STATIC_ATTR_GRID_LIST[1]] = tmp.country
        await asyncio.sleep(DEFAULT_COOLDOWN_INTERVAL)

        if config[CONF_OPTIMIZERS]:
            register = ATTR_NB_OPTIMIZERS
            static_attributes[register] = (await inverter.get(register)).value
            _LOGGER.debug("get sensor static attribute: %s", register)
            await asyncio.sleep(DEFAULT_COOLDOWN_INTERVAL)

    except ConnectionException as ex:
        _LOGGER.error("could not connect to Huawei inverter: %s", ex)
        await asyncio.sleep(DEFAULT_RECONNECT_INTERVAL)
        return False

    except ReadException as ex:
        _LOGGER.error("could not get register '%s': %s", register, ex)
        await asyncio.sleep(DEFAULT_RECONNECT_INTERVAL)
        return False

    _LOGGER.debug("created inverter")

    huawei_solar_sensor = HuaweiSolarSensor(
        inverter=inverter,
        optimizers_installed=config[CONF_OPTIMIZERS],
        battery_installed=config[CONF_BATTERY],
        static_attributes=static_attributes,
    )

    entities = [
        huawei_solar_sensor,
        HuaweiSolarDailyYieldSensor(
            inverter=inverter,
            unit=ENERGY_KILO_WATT_HOUR,
            icon="mdi:solar-power",
            device_class=DEVICE_CLASS_ENERGY,
            parent_sensor=huawei_solar_sensor,
            register=ATTR_DAILY_YIELD,
            name_prefix=static_attributes["model_name"] + "_daily_yield",
            state_class=STATE_CLASS_MEASUREMENT,
        ),
        HuaweiSolarEntitySensor(
            inverter=inverter,
            unit=ENERGY_KILO_WATT_HOUR,
            icon="mdi:solar-power",
            device_class=DEVICE_CLASS_ENERGY,
            parent_sensor=huawei_solar_sensor,
            register=ATTR_ACCUMULATED_YIELD,
            name_prefix=static_attributes["model_name"] +"_total_yield",
        ),
        HuaweiSolarEntitySensor(
            inverter=inverter,
            unit=ENERGY_KILO_WATT_HOUR,
            icon="mdi:solar-power",
            device_class=DEVICE_CLASS_ENERGY,
            parent_sensor=huawei_solar_sensor,
            register=ATTR_GRID_EXPORTED,
            name_prefix=static_attributes["model_name"] + "_grid_exported",
        ),
        HuaweiSolarEntitySensor(
            inverter=inverter,
            unit=ENERGY_KILO_WATT_HOUR,
            icon="mdi:solar-power",
            device_class=DEVICE_CLASS_ENERGY,
            parent_sensor=huawei_solar_sensor,
            register=ATTR_GRID_ACCUMULATED,
            name_prefix=static_attributes["model_name"] + "_grid_accumulated",
        ),
    ]

    if config[CONF_BATTERY]:
        entities.extend(
            [
                HuaweiSolarEntitySensor(
                    inverter=inverter,
                    unit=POWER_WATT,
                    icon="mdi:solar-power",
                    device_class=DEVICE_CLASS_POWER,
                    parent_sensor=huawei_solar_sensor,
                    register=ATTR_STORAGE_CHARGE_DISCHARGE_POWER,
                ),
                HuaweiSolarEntitySensor(
                    inverter=inverter,
                    unit=ENERGY_KILO_WATT_HOUR,
                    icon="mdi:solar-power",
                    device_class=DEVICE_CLASS_ENERGY,
                    parent_sensor=huawei_solar_sensor,
                    register=ATTR_STORAGE_TOTAL_CHARGE,
                ),
                HuaweiSolarEntitySensor(
                    inverter=inverter,
                    unit=ENERGY_KILO_WATT_HOUR,
                    icon="mdi:solar-power",
                    device_class=DEVICE_CLASS_ENERGY,
                    parent_sensor=huawei_solar_sensor,
                    register=ATTR_STORAGE_TOTAL_DISCHARGE,
                ),
            ]
        )

    async_add_entities(entities, True)
    _LOGGER.debug("added entities")


class HuaweiSolarSensor(Entity):
    def __init__(
        self, inverter, optimizers_installed, battery_installed, static_attributes
    ):
        self._inverter = inverter
        self._optimizers_installed = optimizers_installed
        self._battery_installed = battery_installed
        self._hidden = False
        self._unit = POWER_WATT
        self._icon = "mdi:solar-power"
        self._available = False
        self._state = None
        self.sensor_states = {}
        self._attributes = static_attributes
        self._name = (
            self._attributes["model_name"] # + "_" + self._attributes["serial_number"]
        )
        self._unique_id = self._name
        self._pv_strings_voltage = [None] * self._attributes[ATTR_NB_PV_STRINGS]
        self._pv_strings_current = [None] * self._attributes[ATTR_NB_PV_STRINGS]

    @property
    def available(self):
        """Return True if entity is available."""
        return self._available

    @property
    def unique_id(self):
        """Unique ID of the Huawei Solar sensor"""
        return self._unique_id

    @property
    def name(self):
        return self._name

    @property
    def icon(self):
        return self._icon

    @property
    def state(self):
        return self._state

    @property
    def device_class(self):
        return DEVICE_CLASS_POWER

    @property
    def extra_state_attributes(self):
        attribute_list = DYNAMIC_ATTR_LIST + STATIC_ATTR_LIST + STATIC_ATTR_GRID_LIST
        attribute_list.append(ATTR_NB_PV_STRINGS)

        if self._optimizers_installed:
            attribute_list = attribute_list + [
                ATTR_NB_OPTIMIZERS,
                ATTR_NB_ONLINE_OPTIMIZERS,
            ]

        if self._battery_installed:
            attribute_list = attribute_list + BATTERY_ATTR_LIST

        attributes = {key: self._attributes.get(key, None) for key in attribute_list}

        for i in range(int(self._attributes[ATTR_NB_PV_STRINGS] or 0)):
            attributes[f"pv_string_{i+1:02}_voltage"] = self._pv_strings_voltage[i]
            attributes[f"pv_string_{i+1:02}_current"] = self._pv_strings_current[i]

        return attributes

    @property
    def unit_of_measurement(self):
        return self._unit

    async def async_update(self):
        try:
            self._state = (await self._inverter.get(STATE_REGISTER)).value
            self._available = True
            await asyncio.sleep(DEFAULT_COOLDOWN_INTERVAL)
        except (ReadException, ConnectionException) as ex:
            self._available = False
            _LOGGER.error("could not get register '%s': %s", STATE_REGISTER, ex)
            await asyncio.sleep(DEFAULT_RECONNECT_INTERVAL)

        for register in DYNAMIC_ATTR_LIST:
            try:
                self._attributes[register] = (await self._inverter.get(register)).value
                _LOGGER.debug("get register: %s = %s", register, self._attributes[register])
                await asyncio.sleep(DEFAULT_COOLDOWN_INTERVAL)
            except (ReadException, ConnectionException) as ex:
                _LOGGER.error("could not get register '%s': %s", register, ex)
                await asyncio.sleep(DEFAULT_RECONNECT_INTERVAL)

        for i in range(int(self._attributes[ATTR_NB_PV_STRINGS] or 0)):
            try:
                register = f"pv_{i+1:02}_voltage"
                self._pv_strings_voltage[i] = (await self._inverter.get(register)).value
                _LOGGER.debug("get register: %s", register)
                await asyncio.sleep(DEFAULT_COOLDOWN_INTERVAL)
                register = f"pv_{i+1:02}_current"
                self._pv_strings_current[i] = (await self._inverter.get(register)).value
                _LOGGER.debug("get register: %s", register)
                await asyncio.sleep(DEFAULT_COOLDOWN_INTERVAL)
            except (ReadException, ConnectionException) as ex:
                _LOGGER.error("could not get register %s", ex)
                await asyncio.sleep(DEFAULT_RECONNECT_INTERVAL)

        if self._optimizers_installed:
            try:
                self._attributes[ATTR_NB_ONLINE_OPTIMIZERS] = (
                    await self._inverter.get(ATTR_NB_ONLINE_OPTIMIZERS)
                ).value
                _LOGGER.debug("get register: %s", register)
                await asyncio.sleep(DEFAULT_COOLDOWN_INTERVAL)
            except (ReadException, ConnectionException) as ex:
                _LOGGER.error(
                    "could not get register '%s': %s", ATTR_NB_ONLINE_OPTIMIZERS, ex
                )
                await asyncio.sleep(DEFAULT_RECONNECT_INTERVAL)

        # values for other entity sensors
        # Asynchronously calling update from a different sensors does not work
        for register in ENTITY_SENSOR_LIST:
            try:
                self.sensor_states[register] = (
                    await self._inverter.get(register)
                ).value
                _LOGGER.debug("get register: %s", register)
                await asyncio.sleep(DEFAULT_COOLDOWN_INTERVAL)
            except (ReadException, ConnectionException) as ex:
                _LOGGER.error("could not get register '%s': %s", register, ex)
                await asyncio.sleep(DEFAULT_RECONNECT_INTERVAL)

        if self._battery_installed:
            for register in BATTERY_ENTITY_SENSOR_LIST:
                try:
                    self.sensor_states[register] = (
                        await self._inverter.get(register)
                    ).value
                    _LOGGER.debug("get register: %s", register)
                    await asyncio.sleep(DEFAULT_COOLDOWN_INTERVAL)
                except (ReadException, ConnectionException) as ex:
                    _LOGGER.error("could not get register '%s': %s", register, ex)
                    await asyncio.sleep(DEFAULT_RECONNECT_INTERVAL)

            for register in BATTERY_ATTR_LIST:
                try:
                    self._attributes[register] = (
                        await self._inverter.get(register)
                    ).value
                    _LOGGER.debug("get register: %s", register)
                    await asyncio.sleep(DEFAULT_COOLDOWN_INTERVAL)
                except (ReadException, ConnectionException) as ex:
                    _LOGGER.error("could not get register '%s': %s", register, ex)
                    await asyncio.sleep(DEFAULT_RECONNECT_INTERVAL)


class HuaweiSolarEntitySensor(Entity):
    def __init__(
        self,
        inverter,
        unit,
        icon,
        device_class,
        parent_sensor,
        register,
        name_prefix=None,
        state_class=STATE_CLASS_TOTAL_INCREASING,
    ):
        self._inverter = inverter
        self._hidden = False
        self._available = False
        self._unit = unit
        self._icon = icon
        self._parent_sensor = parent_sensor
        self._register = register
        if name_prefix:
            self._name = (
                name_prefix # + "_" + self._parent_sensor._attributes[ATTR_SERIAL_NUMBER]
            )
        else:
            self._name = (
                register + "_" + self._parent_sensor._attributes[ATTR_SERIAL_NUMBER]
            )
        self._unique_id = self._name
        self._device_class = device_class
        self._state_class = state_class

    @property
    def unique_id(self):
        """Unique ID of the Huawei Solar entity sensor"""
        return self._unique_id

    @property
    def name(self):
        return self._name

    @property
    def icon(self):
        return self._icon

    @property
    def state(self):
        return self._parent_sensor.sensor_states.get(self._register, None)

    @property
    def unit_of_measurement(self):
        return self._unit

    @property
    def extra_state_attributes(self):
        return {
            ATTR_STATE_CLASS: self._state_class,
        }

    @property
    def device_class(self):
        return self._device_class

    @property
    def available(self):
        """Return True if entity is available."""
        return self._parent_sensor.available


class HuaweiSolarDailyYieldSensor(HuaweiSolarEntitySensor):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    @property
    def extra_state_attributes(self):
        system_time = self._parent_sensor._attributes.get("system_time", None)
        if system_time is not None:
            last_reset = system_time.replace(hour=0, minute=0, second=0)
        else:
            last_reset = None

        return {
            **super().extra_state_attributes,
            ATTR_LAST_RESET: last_reset,
        }

**Comment by titidnh** [comment]
[sensor.txt](https://github.com/Emilv2/huawei_solar/files/11734311/sensor.txt)

**Comment by 111lisu** [comment]
@agmuz  Ja przełożyłem na https://github.com/wlcrs/huawei_solar/ i śmiga aż miło i to bez grzebania w konfigu.

**Comment by testgit1981** [comment]
Worked for me too

**Comment by garzew2** [comment]
`Logger: homeassistant.components.sensor
Source: custom_components/huawei_solar/sensor.py:181
Integration: Sensor (documentation, issues)
First occurred: 22:34:59 (1 occurrences)
Last logged: 22:34:59

Error while setting up huawei_solar platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/registers.py", line 92, in decode
    result = self.unit[result]
             ~~~~~~~~~^^^^^^^^
KeyError: 303

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/huawei_solar/sensor.py", line 181, in async_setup_platform
    tmp = (await inverter.get(register)).value
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 215, in get
    return (await self.get_multiple([name], slave))[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 254, in get_multiple
    result = [await self._decode_response(registers[0], decoder)]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/huawei_solar.py", line 207, in _decode_response
    result = reg.decode(decoder, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huawei_solar/registers.py", line 94, in decode
    raise DecodeError from err
huawei_solar.exceptions.DecodeError
`
Hello. I still have problem when upgaded HomeAsistant.
I updated a huawei-solar when emilv2 make changes but it won't help in my system. I also copy full sensor.py from [titidnh](https://github.com/titidnh) but no progress. Can anyone help to solve this problem?
