### ISSUE TITLE
Using SDongleA-05 without internet access

### ISSUE THREAD

**Issue by Schaussi** [Emilv2/huawei_solar#37]
Hi,

thanks to your HA integration, I get all needed data from the inverter directly via local network.
So I see no reason why the dongle should have internet access (also due to security reasons), therefore I disabled WAN access for this device within the firewall.

This scenario works fine for some hours, then the dongle loses LAN reachability more and more (some ping loss first, then after some more hours it is no more reachable and I have to reconnect it (USB)).

This issue does not appear when the dongle has full internet access. So my guess is like the dongle has an internal queue which gets full if it cannot send to FusionSolar, so the system freezes after some time.

Did you also experience this behavior with your dongles?
Sorry if this is a bit off-topic, but EU Huawei support does not understand my explanations at all...

Thank you

**Comment by Evka2k** [comment]
> Hi,
> 
> thanks to your HA integration, I get all needed data from the inverter directly via local network. So I see no reason why the dongle should have internet access (also due to security reasons), therefore I disabled WAN access for this device within the firewall.
> 
> This scenario works fine for some hours, then the dongle loses LAN reachability more and more (some ping loss first, then after some more hours it is no more reachable and I have to reconnect it (USB)).
> 
> This issue does not appear when the dongle has full internet access. So my guess is like the dongle has an internal queue which gets full if it cannot send to FusionSolar, so the system freezes after some time.
> 
> Did you also experience this behavior with your dongles? Sorry if this is a bit off-topic, but EU Huawei support does not understand my explanations at all...
> 
> Thank you

My sun2000-8ktl-m0 smart dongle via FE. Firewall limit access to cloud services. HA+sun2000 component works for me. Looks like without any problems.

**Comment by Schaussi** [comment]
FYI, I have been in contact with Huawei support for some weeks now, it is quite tedious... but basically they have acknowledged the issue.
Blocking internet access for the dongle makes it retry many times and after about one day of trying it freezes.

Support told me to 
- disable the management system option via FusionSolar app -> this is not possible in the current version (seems they sent old screenshots).
- remove the management system url via FusionSolar app -> clearing this field also is not possible (seems they did not even test it).

Today I tried current dongle firmware SPC124, which does not even offer an open TCP port 502, so I reverted to SPC123.

While I am waiting for further support answers, I am currently trying 127.0.0.1 as management system url, not knowing yet how long the dongle will stay online.

**Comment by Evka2k** [comment]
I run some dumb tcp server (https://gist.github.com/logasja/97bddeb84879b30519efb0c66b4db159) on my local machine(some 192.168.0.10) and rewrite on router DNS record for "intl.fusionsolar.huawei.com" to that machine (192.168.0.10). Huawei inverter is happy with that (management system connection successful):
![happy](https://user-images.githubusercontent.com/77075640/141201667-39e8c395-6532-4956-8611-466aa34227df.jpg)

It could be another approach for sun2000 component - act as management system. As i understand protocol is something similar to modbus-tcp but inverter itself connects to server.

**Comment by Emilv2** [comment]
I don't think provinding a webserver is possible within HA, but I could be wrong. Can you get any data out of the inverter using your server?

**Comment by Evka2k** [comment]
dongle sends some hello packets with firmware version & so on. I did not tried to send back something. It was possible to sniff communication with server earlier it was not encrypted, but now it's TLS. 

`./tcpserver.py                                                                                                                
Chat server started on port 27251                                                                                                       
Client (172.16.0.12, 52432) connected                                                                                                   
b'\x00\x00\x00\x00\x00[\x00AD\x00V\x01\x00\x01\x00\x0b\xa2\x00\x01\x01\x00\x12J1=SDongleA-05;2=V100R001C00SPC120;3=P1.15-D50.0;4=HV20500
33097;5=100;6=1.3'                                                                                                                      
b'\x00\x00\x00\x00\x00[\x00AD\x00V\x01\x00\x02\x00\x0b\xa3\x00\x01\x01\x00\x12J1=SDongleA-05;2=V100R001C00SPC120;3=P1.15-D50.0;4=HV20500
33097;5=100;6=1.3'                                                                                                                      
b"\x0b\x00\x00\x00\x01,dAG\x01'\x11e\x00\r\x11\x0b\x00\x00\x00\x00\x01\x14o\x19\x00\x01\x00\x00\x00\x01\x02\x00\x01\x01\x00\x00\xd3a\x8c
V\x8b\x00\x00\x00UE\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\x00\x00\x00\x00\x00\x00\x00\nc\x06\x00\n\xe2|\x00\x00\x02\x8
4\x00\x00\x12\x90\x00\t\xbc\x9b\x00\x00\xff\xff\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00d\x01\x00\x003a\x8cV\x8b\x00\x00\x00\x0b\xa3\xff\xff\x00\x00\x00\x00\xff\xff\xff\xff\x7f\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\nc\x06\x00\x00\x00\x00"`

**Comment by Evka2k** [comment]
I found some old *.cap file. After sending
`b'\xb7\xf4\x00\x00\x00\x05\x00\x2b\x0e\x01\x00'`
I received
` b'\xb7\xf4\x00\x00\x00V\x00+\x0e\x01\x01\x00\x00\x08\x00\x06HUAWEI\x01\x0bSDongleA-05\x02\x11V100R001C00SPC120\x03\x02\x00\x07\x10\x14HV2050033097\x00\x00\x00\x00\x00\x00\x00\x00\x11\x02\x0b\xa3\x12\x02\x00\x00\x13\x02\x00\x01' `

Looks like the same as my in my pcap file modbus/tcp :)

![cap_1](https://user-images.githubusercontent.com/77075640/141208446-c93ddff3-1878-485f-8d59-a2399607f46b.jpg)
![cap_2](https://user-images.githubusercontent.com/77075640/141208604-9f2f821a-cc7f-44dd-8443-e593c52ec489.jpg)
![cap_3](https://user-images.githubusercontent.com/77075640/141208461-80837915-3733-4f5c-9cd1-cec28cee17a9.jpg)

**Comment by Emilv2** [comment]
How would you run a TCP server in HA as an integration? You would also have to change the DNS and break the Huawei cloud. Multiple inverters work already as far as I know.

The goal is to make this an official integration, and I don't think such a setup would qualify.

It could be interesting for debugging purposes though. Do you have any optimizers? I never got getting the optimizer data to work.

**Comment by Evka2k** [comment]
I don't have optimizers.

I found some tcp server example here. https://github.com/npope/home-assistant-crestron-component/blob/master/custom_components/crestron/crestron.py

**Comment by Schaussi** [comment]
For my purpose the dummy TCP server solution is working very fine (currently I am running Hercules utility on a Windows server in my local network).
I have entered its IP in FusionSolar app as the management system URL, and to be safe also my local DNS server redirects intl.fusionsolar.huawei.com to this IP.
The dongle contacts the TCP server every 10 - 20 minutes and does not seem to expect a useful response, anyway I never needed a reset in the last few days.

FYI, messages coming from the dongle are looking like (TLS disabled):

> =1.3[ADVÅíJ1=SDongleA-05;2=V100R001C00SPC123;3=P1.15-D50.0;4=BT20C00xxxxx;5=100;6=1.3[ADVÐíJ1=SDongleA-05;2=V100R001C00SPC123;3=P1.15-D50.0;4=BT20C00xxxxx;5=100;6=1.3[ADVÛíJ1=SDongleA-05;2=V100R001C00SPC123;3=P1.15-D50.0;4=BT20C00xxxxx;5=100;6=1.3[ADVæíJ1=SDongleA-05;2=V100R001C00SPC123;3=P1.15-D50.0;4=BT20C00xxxxx;5=100;6=1.3[ADVñíJ1=SDongleA-05;2=V100R001C00SPC123;3=P1.15-D50.0;4=BT20C00xxxxx;5=100;

I have optimizers; if you want me to test any TCP requests etc., please tell me.
