### ISSUE TITLE
Connection refused when connecting

### ISSUE THREAD

**Issue by Breina** [Emilv2/huawei_solar#39]
Just got one installed yesterday, but I can't seem to connect.

huawei_solar version: 0.2.1
Inverter version: SPC135
Battery version: SPC104
Optimizer version: SPC002
MBUS version: SPC300

I can get a direct WiFi connection and into the installer portal. My Router reports it using IP address 192.168.1.40 and the inverter reports connecting to the Huawei servers successfully. Telnet to port 502 also with `Connection refused`.

```
Logger: pymodbus.client.sync
Source: /usr/local/lib/python3.9/site-packages/pymodbus/client/sync.py:218
First occurred: October 21, 2021, 17:57:48 (2 occurrences)
Last logged: October 21, 2021, 17:57:50

Connection to (192.168.1.40, 502) failed: [Errno 111] Connection refused
```

```
Logger: huawei_solar.huawei_solar
Source: /usr/local/lib/python3.9/site-packages/huawei_solar/huawei_solar.py:297
First occurred: October 21, 2021, 17:57:50 (1 occurrences)
Last logged: October 21, 2021, 17:57:50

failed to connect to device, is the host correct?
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/huawei_solar/huawei_solar.py", line 293, in read_register
    response = self.client.read_holding_registers(
  File "/usr/local/lib/python3.9/site-packages/pymodbus/client/common.py", line 114, in read_holding_registers
    return self.execute(request)
  File "/usr/local/lib/python3.9/site-packages/pymodbus/client/sync.py", line 108, in execute
    raise ConnectionException("Failed to connect[%s]" % (self.__str__()))
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.1.40:502)]
```

```
Logger: homeassistant.components.sensor
Source: custom_components/huawei_solar/sensor.py:135
Integration: Sensor (documentation, issues)
First occurred: October 21, 2021, 17:57:50 (1 occurrences)
Last logged: October 21, 2021, 17:57:50

Error while setting up huawei_solar platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/huawei_solar/huawei_solar.py", line 293, in read_register
    response = self.client.read_holding_registers(
  File "/usr/local/lib/python3.9/site-packages/pymodbus/client/common.py", line 114, in read_holding_registers
    return self.execute(request)
  File "/usr/local/lib/python3.9/site-packages/pymodbus/client/sync.py", line 108, in execute
    raise ConnectionException("Failed to connect[%s]" % (self.__str__()))
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.1.40:502)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/huawei_solar/sensor.py", line 120, in setup_platform
    HuaweiSolarSensor(inverter, config[CONF_OPTIMIZERS], config[CONF_BATTERY])
  File "/config/custom_components/huawei_solar/sensor.py", line 135, in __init__
    self._name = self._inverter.get("model_name").value
  File "/usr/local/lib/python3.9/site-packages/huawei_solar/huawei_solar.py", line 265, in get
    response = self.read_register(reg.register, reg.length)
  File "/usr/local/lib/python3.9/site-packages/huawei_solar/huawei_solar.py", line 298, in read_register
    raise ConnectionException(ex)
huawei_solar.huawei_solar.ConnectionException: Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.1.40:502)]
```

## System Health

version | core-2021.10.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.70
arch | x86_64
timezone | Europe/Brussels

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4967
Installed Version | 1.15.1
Stage | running
Available Repositories | 892
Installed Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.5
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.0
docker_version | 20.10.7
disk_total | 30.8 GB
disk_used | 8.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Check Home Assistant configuration (3.8.0), Terminal & SSH (9.2.1), AppDaemon 4 (0.7.0), Samba share (9.5.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 5
mode | storage

</details>

**Comment by arboeh** [comment]
> Problem solved! I had to update the dongle. Turns out the dongle itself has its own direct WiFi connection which is only available the first 3 minutes that it's plugged in.
> 
> 1. Unplug and replug the dongle.
> 2. Connect it through its direct WiFi (which starts with SDongle, takes a while to show up), default password "Changeme".
> 3. Open up the Fusion solar app > ... > Comissioning > default password "00000a".
> 4. Maintenance > Upgrade device
> 5. Select the Firmware attached here (SPC123).
> 6. Confirm and wait for it to finish.
>    [SDongle_V100R001C00SPC123_package.zip](https://github.com/Emilv2/huawei_solar/files/7411129/SDongle_V100R001C00SPC123_package.zip)
> 
> Hope this helps for future internet people! :)

Unfortunately not possible to downgrade to SPC123...

![Screenshot_2022-10-09-13-55-19-05_81922fc742ed931ad7de97e3169fc6f0](https://user-images.githubusercontent.com/12322114/194755826-44a83771-4acb-4236-9705-dc2104b04cd4.jpg)
![Screenshot_2022-10-09-13-55-22-94_81922fc742ed931ad7de97e3169fc6f0](https://user-images.githubusercontent.com/12322114/194755855-8553ac8a-d8bf-4c8f-a8c6-c4ee73f76baa.jpg)
