### ISSUE TITLE
Entity failing to load/function

### ISSUE THREAD

**Issue by claymen** [Emilv2/huawei_solar#45]
After updating to 55f1e67 I am getting no entity or sensor setup, and with the sensor added I get the following error when restarting the core. Running under HASS OS, core-2021.11.2

![image](https://user-images.githubusercontent.com/123596/141054113-092e62bc-d310-445d-9d7f-c4eb0ccc416f.png)

Example of the previously working config entry.

>   - platform: huawei_solar
>     host: x.x.x.x
>     optimizers: false
>     battery: false
>     slave: 1

**Comment by Emilv2** [comment]
That should be fixed now.

**Comment by claymen** [comment]
> That should be fixed now.

Awesome, all working. Much appreciated for the fast update. Let me know if you need any other details pulled.
