### ISSUE TITLE
No data after latest update

### ISSUE THREAD

**Issue by erikwachters** [Emilv2/huawei_solar#49]
Hi,

The sensor is not there and this is all over the log (every 6sec):
WARNING (MainThread) [pymodbus.client.asynchronous.async_io] Failed to connect: [Errno 113] Connect call failed ('192.168.1.249', 502)

Is there any way to revert to the version before you made the separate sensors so I only have one? That version worked perfect.

**Comment by Emilv2** [comment]
If you don't use HACS you can just copy the correct commit. If you use HACS I don't know, I have never used HACS.

There didn't change anything fundamental between the versions, so I suspect your issue lies somewhere else. If not that's an issue that should be fixed instead of just not updating.

**Comment by Emilv2** [comment]
Ok, strange, I can't find this warning `Connect call failed` at all in the pymodbus code.

**Comment by erikwachters** [comment]
Ok I think it's solved by removing __pycache__ from the folder and restart HASS.
