### ISSUE TITLE
negative value (daily_yield) at midnight

### ISSUE THREAD

**Issue by rickleka** [Emilv2/huawei_solar#50]
Every night a negative value (solar production, daily yield) occur. probably due the daily-yield reset.

![negative_value_dailyyield_midnight reset]
(https://user-images.githubusercontent.com/62348417/142217534-ed7e1d0b-e879-439f-a359-879e7bafc129.PNG)

**Comment by JacoboSanchez** [comment]
I think this is due to some gap between the inverter's system time and the HA's time. A way to fix this is to use the total_yield instead of daily. Another option is to check your inverter's system time and see if you can adjust it

**Comment by Emilv2** [comment]
I made it so that it uses the inverter's system time, but I never tested it thoroughly so there could be issues.
