### ISSUE TITLE
device_state_attributes HA 2021.12

### ISSUE THREAD

**Issue by luzik** [Emilv2/huawei_solar#66]
Entity sensor.sun2000_5ktl_m1_gin300_5ktl_m1_hv2140422021 (<class 'custom_components.huawei_solar.sensor.HuaweiSolarSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by powertoaster** [comment]
Ditto
<class 'custom_components.huawei_solar.sensor.HuaweiSolarSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by luzik** [comment]
Any news on this ? Entity is unavailable because of this error.
