### ISSUE TITLE
Can't find it on HACS

### ISSUE THREAD

**Issue by elektrinis** [Emilv2/huawei_solar#7]
I like the idea of easy install and maintenance. In the info it says huawei_solar is available on HACS, yet I am unable to find it.
Am I doing something wrong?

**Comment by Emilv2** [comment]
I haven't used HACS myself. @fishingbit Something else we need to do here to get this working?

**Comment by gieljnssns** [comment]
@elektrinis 
You have to add a [custom repository](https://hacs.xyz/docs/faq/custom_repositories)

**Comment by elektrinis** [comment]
That worked. Thanks.
