### ISSUE TITLE
Warning with 2021.4.x

### ISSUE THREAD

**Issue by maury77** [Emilv2/huawei_solar#9]
[homeassistant.loader] No 'version' key in the manifest file for custom integration 'huawei_solar'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'huawei_solar'

**Comment by Stea73** [comment]
Hi, please add version number to the manifest as the integration (that is great, btw) is not loading

**Comment by Emilv2** [comment]
Should be fixed now since there is a version key
