### ISSUE TITLE
Integration stop working after update HA from 2.8.6 to 2.8.7

### ISSUE THREAD

**Issue by razvanu** [Emilv2/huawei_solar#94]
```
Logger: homeassistant.setup
Source: setup.py:184
First occurred: 4:21:04 PM (1 occurrences)
Last logged: 4:21:04 PM

Setup failed for custom integration huawei_solar: Requirements for huawei_solar not found: ['huawei-solar==2.0.0rc6'].

```
Hi, Can you help with this error ?

**Comment by Emilv2** [comment]
Some older versions have been deleted, but I don't really understand why you have this issue since the version in requirements is `huawei-solar>=1.2.0,<2.0.0`

**Comment by razvanu** [comment]
I've deleted the folder from custom_components, and will try to reintegrate, but probably i've lost the energy logs.

**Comment by razvanu** [comment]
And now it's gone completely from integration.

![image](https://user-images.githubusercontent.com/15201014/186943990-b8989863-b773-4433-b7c5-af5b0465bd53.png)

**Comment by razvanu** [comment]
restored a backup, two weeks later , but still nothing

![image](https://user-images.githubusercontent.com/15201014/186993172-18268dbc-d0ef-4263-9cba-22946bb721f1.png)

**Comment by Emilv2** [comment]
Yes, huawei-solar 2.0.0rc6 has unfortunately been deleted, you won't be able to install that. Which version of the plugin do you have that it requires this version?

**Comment by razvanu** [comment]
How to find plugin version ? Where to look ? 10x

**Comment by Emilv2** [comment]
It's in manifest.json

**Comment by razvanu** [comment]
```
  "domain": "huawei_solar",
  "name": "huawei_solar",
  "documentation": "https://github.com/Emilv2/huawei_solar",
  "dependencies": [],
  "codeowners": ["Emilv2"],
  "requirements": ["huawei-solar>=1.2.0,<2.0.0"],
  "version": "1.2.4"
}

```

**Comment by wlcrs** [comment]
I have the impression that you had installed [my plugin](https://github.com/wlcrs/huawei_solar) earlier and have now tried to update by incorrectly getting the code from this repository. Please update to the latest version from my repository instead. Maybe consider using HACS for easy updating in the future?

**Comment by razvanu** [comment]
I have HACS installed, now will reinstall

![image](https://user-images.githubusercontent.com/15201014/187049958-10efeda6-4954-4db4-a906-bc9c51f284e1.png)

**Comment by razvanu** [comment]
Solved, error on installation, you're right about this. Now i've installed from HACS. Thank you.
